module.exports = [
    {
        name:'TWO_CROWS',
        bullish:{
            strength:null,
            theoreticalType:null,
            testedType:null
        },
        bearish:{
            strength:104-61,
            theoreticalType:'BEARISH_REVERSAL',
            testedType:'BEARISH_REVERSAL'
        }
    },
    {
        name:'THREE_BLACK_CROWS',
        bullish:{
            strength:null,
            theoreticalType:null,
            testedType:null
        },
        bearish:{
            strength:104-3,
            theoreticalType:'BEARISH_REVERSAL',
            testedType:'BEARISH_REVERSAL'
        }
    },
    {
        name:'THREE_INSIDE',
        bullish:{
            strength:104-20,
            theoreticalType:'BULLISH_REVERSAL',
            testedType:'BULLISH_REVERSAL'
        },
        bearish:{
            strength:104-56,
            theoreticalType:'BEARISH_REVERSAL',
            testedType:'BEARISH_REVERSAL'
        }
    },
    {
        name:'THREE_LINE_STRIKE',
        bullish:{
            strength:104-2,
            theoreticalType:'BULLISH_CONTINUATION',
            testedType:'BEARISH_REVERSAL'
        },
        bearish:{
            strength:104-1,
            theoreticalType:'BEARISH_CONTINUATION',
            testedType:'BULLISH_REVERSAL'
        }
    },
    {
        name:'THREE_OUTSIDE',
        bullish:{
            strength:104-34,
            theoreticalType:'BULLISH_REVERSAL',
            testedType:'BULLISH_REVERSAL'
        },
        bearish:{
            strength:104-39,
            theoreticalType:'BEARISH_REVERSAL',
            testedType:'BEARISH_REVERSAL'
        }
    },
    {
        name:'THREE_STARS_IN_THE_SOUTH',
        bullish:{
            strength:104-103,
            theoreticalType:'BULLISH_REVERSAL',
            testedType:'BULLISH_REVERSAL'
        },
        bearish:{
            strength:null,
            theoreticalType:null,
            testedType:null
        }
    },
    {
        name:'THREE_WHITE_SOLDIERS',
        bullish:{
            strength:104-32,
            theoreticalType:'BULLISH_REVERSAL',
            testedType:'BULLISH_REVERSAL'
        },
        bearish:{
            strength:null,
            theoreticalType:null,
            testedType:null
        }
    },
    {
        name:'ABANDONED_BABY',
        bullish:{
            strength:104-9,
            theoreticalType:'BULLISH_REVERSAL',
            testedType:'BULLISH_REVERSAL'
        },
        bearish:{
            strength:104-64,
            theoreticalType:'BEARISH_REVERSAL',
            testedType:'BEARISH_REVERSAL'
        }
    },
    {
        name:'ADVANCE_BLOCK',
        bullish:{
            strength:null,
            theoreticalType:null,
            testedType:null
        },
        bearish:{
            strength:104-54,
            theoreticalType:'BEARISH_REVERSAL',
            testedType:'BULLISH_CONTINUATION'
        }
    },
    {
        name:'BELT_HOLD',
        bullish:{
            strength:104-62,
            theoreticalType:'BULLISH_REVERSAL',
            testedType:'BULLISH_REVERSAL'
        },
        bearish:{
            strength:104-63,
            theoreticalType:'BEARISH_REVERSAL',
            testedType:'BEARISH_REVERSAL'
        }
    },
    {
        name:'DARK_CLOUD_COVER',
        bullish:{
            strength:null,
            theoreticalType:null,
            testedType:null
        },
        bearish:{
            strength:104-22,
            theoreticalType:'BEARISH_REVERSAL',
            testedType:'BEARISH_REVERSAL'
        }
    },
    {
        name:'HARAMI',
        bullish:{
            strength:104-38,
            theoreticalType:'BULLISH_REVERSAL',
            testedType:'BULLISH_REVERSAL'
        },
        bearish:{
            strength:104-72,
            theoreticalType:'BEARISH_REVERSAL',
            testedType:'BULLISH_CONTINUATION'
        }
    },
    {
        name:'PIERCING',
        bullish:{
            strength:104-13,
            theoreticalType:'BULLISH_REVERSAL',
            testedType:'BULLISH_REVERSAL'
        },
        bearish:{
            strength:null,
            theoreticalType:null,
            testedType:null
        }
    },
    {
        name:'ENGULFING',
        bullish:{
            strength:104-84,
            theoreticalType:'BULLISH_REVERSAL',
            testedType:'BULLISH_REVERSAL'
        },
        bearish:{
            strength:104-91,
            theoreticalType:'BEARISH_REVERSAL',
            testedType:'BEARISH_REVERSAL'
        }
    }
];